const now = (): string => new Date().toISOString();

//차트 임시 데이터 추가
export const chartData = [
  { year: "1학년 1학기", p1: 186, p2: 80 },
  { year: "1학년 2학기", p1: 305, p2: 200 },
  { year: "2학년 1학기", p1: 237, p2: 120 },
  { year: "2학년 2학기", p1: 73, p2: 190 },
  { year: "3학년 1학기", p1: 209, p2: 130 },
  { year: "3학년 2학기", p1: 214, p2: 140 },
  { year: "4학년 1학기", p1: 29, p2: 130 },
  { year: "4학년 2학기", p1: 214, p2: 14 },
];

// 단과대학
export const colleges = [
  {
    collegeSeq: 1001,
    univSeq: 100,
    collegeName: "공과대학",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    collegeSeq: 1002,
    univSeq: 100,
    collegeName: "자연과학대학",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    collegeSeq: 2001,
    univSeq: 200,
    collegeName: "경상대학",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    collegeSeq: 3001,
    univSeq: 300,
    collegeName: "공과대학",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 사용자
export const users = [
  {
    userSeq: 1,
    userEmail: "alice@example.com",
    userId: "alice",
    userPwd: "pass1234",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    userSeq: 2,
    userEmail: "bob@example.com",
    userId: "bob",
    userPwd: "pass1234",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 교수
export const profs = [
  {
    profSeq: 9001,
    deptSeq: 100101,
    profName: "김개발",
    profEmail: "kimdev@cnu.ac.kr",
    homePage: "",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    profSeq: 9002,
    deptSeq: 100101,
    profName: "박테스트",
    profEmail: "park@cnu.ac.kr",
    homePage: "",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    profSeq: 9003,
    deptSeq: 100102,
    profName: "이전기",
    profEmail: "lee@cnu.ac.kr",
    homePage: "",
    createUser: "admin",
    modifyUser: "admin",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 대학리뷰
export const univReviews = [
  {
    univReviewSeq: 1,
    univSeq: 100,
    food: 4,
    dorm: 4,
    conv: 5,
    campus: 4,
    overall: 4,
    reviewTxt: "캠퍼스가 넓고 주변 편의시설이 좋아요",
    aver: 4.2,
    createUser: "alice",
    modifyUser: "alice",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    univReviewSeq: 2,
    univSeq: 200,
    food: 3,
    dorm: 3,
    conv: 4,
    campus: 4,
    overall: 3,
    reviewTxt: "전공 인프라가 좋음",
    aver: 3.4,
    createUser: "bob",
    modifyUser: "bob",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 대학
export const univs = [
  {
    univSeq: 100,
    name: "충남대학교",
    address: "대전광역시 유성구 대학로 99",
    tel: "042-821-5114",
    homePage: "https://www.cnu.ac.kr",
    image: "/images/univ/cnu.png",
    year: "1952",
    studentNum: 17000,
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    univSeq: 200,
    name: "경북대학교",
    address: "대구광역시 북구 대학로 80",
    tel: "053-950-5114",
    homePage: "https://www.knu.ac.kr",
    image: "/images/univ/knu.png",
    year: "1946",
    studentNum: 20000,
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    univSeq: 300,
    name: "전남대학교",
    address: "광주광역시 북구 용봉로 77",
    tel: "062-530-5114",
    homePage: "https://www.jnu.ac.kr",
    image: "/images/univ/jnu.png",
    year: "1952",
    studentNum: 18000,
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    univSeq: 400,
    name: "강원대학교",
    address: "강원특별자치도 춘천시 강원대학길 1",
    tel: "033-250-6114",
    homePage: "https://www.kangwon.ac.kr",
    image: "/images/univ/kangwon.png",
    year: "1947",
    studentNum: 16000,
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    univSeq: 500,
    name: "부산대학교",
    address: "부산광역시 금정구 부산대학로 63번길 2",
    tel: "051-510-5114",
    homePage: "https://www.pusan.ac.kr",
    image: "/images/univ/pusan.png",
    year: "1946",
    studentNum: 19000,
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 학과
export const depts = [
  // 충남대 공과대학
  {
    deptSeq: 100101,
    collegeSeq: 1001,
    deptName: "컴퓨터공학과",
    homePage: "https://computer.cnu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    deptSeq: 100102,
    collegeSeq: 1001,
    deptName: "기계공학과",
    homePage: "https://me.cnu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },

  // 충남대 자연과학대학
  {
    deptSeq: 100201,
    collegeSeq: 1002,
    deptName: "수학과",
    homePage: "https://math.cnu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    deptSeq: 100202,
    collegeSeq: 1002,
    deptName: "화학과",
    homePage: "https://chem.cnu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },

  // 경북대 경상대학
  {
    deptSeq: 200101,
    collegeSeq: 2001,
    deptName: "경제학과",
    homePage: "https://econ.knu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    deptSeq: 200102,
    collegeSeq: 2001,
    deptName: "경영학과",
    homePage: "https://biz.knu.ac.kr",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 강의 평가
export const lectureReviews = [
  {
    lecReviewSeq: 1,
    lecSeq: 101,
    homework: 3,
    lecDifficulty: 4,
    gradeDistribution: 3,
    semester: "2025-1",
    examDifficulty: 4,
    groupProjReq: "Y",
    overallReview: "수업이 매우 유익했습니다.",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    lecReviewSeq: 2,
    lecSeq: 102,
    homework: 2,
    lecDifficulty: 3,
    gradeDistribution: 4,
    semester: "2025-1",
    examDifficulty: 3,
    groupProjReq: "N",
    overallReview: "조금 어려웠지만 이해할 수 있었습니다.",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    lecReviewSeq: 3,
    lecSeq: 103,
    homework: 4,
    lecDifficulty: 5,
    gradeDistribution: 2,
    semester: "2025-1",
    examDifficulty: 5,
    groupProjReq: "Y",
    overallReview: "과제량이 많았고 시험이 어려웠습니다.",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 강의
export const lectures = [
  {
    lecSeq: 101,
    deptSeq: 100101, // 컴퓨터공학과
    profSeq: 9001, // 김개발
    name: "자료구조",
    credit: 3,
    room: "공대 1호관 101",
    semester: "2025-1",
    time: "월/수 10:00-11:30",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    lecSeq: 102,
    deptSeq: 100101, // 컴퓨터공학과
    profSeq: 9002, // 박테스트
    name: "알고리즘",
    credit: 3,
    room: "공대 1호관 102",
    semester: "2025-1",
    time: "화/목 13:00-14:30",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    lecSeq: 103,
    deptSeq: 100102, // 기계공학과
    profSeq: 9003, // 이전기
    name: "열역학",
    credit: 3,
    room: "공대 2호관 201",
    semester: "2025-1",
    time: "월/수 09:00-10:30",
    createUser: "seed",
    modifyUser: "seed",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];

// 교수평가
export const profReviews = [
  {
    profReviewSeq: 1,
    profSeq: 9001,
    userSeq: 1,
    thesisPerf: 4,
    researchPerf: 4,
    thesisReview: "이 형 연구 열심히 함 ㄹㅇ임 ㅋㅋ",
    createUser: "alice",
    modifyUser: "alice",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
  {
    profReviewSeq: 2,
    profSeq: 9002,
    userSeq: 2,
    thesisPerf: 3,
    researchPerf: 5,
    thesisReview:
      "오늘부로 박테스트지지를 철회한다. 오늘부터 지지관계에서 벗어나 박테스트와 나는 한몸으로 일체가 된다. 박테스트에 대한 공격은 나에 대한 공격으로 간주된다. 세상에 70억 명의 박테스트 팬이 있다면, 나는 그들 중 한명일 것이다. 세상에 1억 명의 박테스트 팬이 있다면, 나 또한 그들 중 한 명일 것이다. 세상에 천만 명의 박테스트 팬이 있다면, 나는 여전히 그들 중 한 명일 것이다. 세상에 백 명의 박테스트 팬이 있다면, 나는 아직도 그들 중 한 명일 것이다. 세상에 한 명의 박테스트 팬이 있다면, 그 사람은 아마도 나일 것이다. 세상에 단 한명의 박테스트 팬도 없다면, 나는 그제서야 이 세상에 없는 것이다. 박테스트, 나의 사랑. 박테스트, 나의 빛. 박테스트, 나의 어둠. 박테스트, 나의 삶. 박테스트, 나의 기쁨. 박테스트, 나의 슬픔. 박테스트, 나의 안식. 박테스트, 나의 영혼. 박테스트, 나.",
    createUser: "bob",
    modifyUser: "bob",
    createDate: now(),
    modifyDate: now(),
    deltYn: "N",
  },
];
